SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS mri_cloud DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mri_cloud;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(256) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  enabled CHAR(1) NOT NULL DEFAULT 'Y',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_code VARCHAR(64) NOT NULL UNIQUE,
  role_name VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sys_user_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  role_code VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS patient (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  patient_no VARCHAR(64) NOT NULL UNIQUE,
  account_username VARCHAR(64),
  name VARCHAR(64) NOT NULL,
  gender VARCHAR(16) NOT NULL,
  birth_date DATE,
  phone VARCHAR(32),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0,
  UNIQUE KEY uk_patient_account_username (account_username)
);

CREATE TABLE IF NOT EXISTS mri_contraindication (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  patient_id BIGINT NOT NULL,
  type VARCHAR(64) NOT NULL,
  description VARCHAR(512),
  severity VARCHAR(32),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mri_exam_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  patient_id BIGINT NOT NULL,
  exam_item VARCHAR(128) NOT NULL,
  clinical_diagnosis VARCHAR(256),
  priority VARCHAR(32),
  status VARCHAR(32) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mri_schedule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  exam_order_id BIGINT NOT NULL,
  scanner_room VARCHAR(64) NOT NULL,
  scheduled_at DATETIME NOT NULL,
  technologist VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mri_study (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  exam_order_id BIGINT NOT NULL,
  study_instance_uid VARCHAR(128) NOT NULL UNIQUE,
  description VARCHAR(256),
  status VARCHAR(32) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mri_series (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  study_id BIGINT NOT NULL,
  series_name VARCHAR(128) NOT NULL,
  body_position VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mri_image_file (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  series_id BIGINT NOT NULL,
  file_name VARCHAR(256) NOT NULL,
  storage_path VARCHAR(512) NOT NULL,
  checksum VARCHAR(128),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mri_download_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  study_id BIGINT NOT NULL,
  operator VARCHAR(64) NOT NULL,
  reason VARCHAR(256),
  downloaded_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mri_report (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  exam_order_id BIGINT NOT NULL,
  study_id BIGINT NOT NULL,
  findings TEXT,
  impression TEXT,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0,
  UNIQUE KEY uk_mri_report_exam_order_id (exam_order_id)
);

CREATE TABLE IF NOT EXISTS mri_report_audit_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  report_id BIGINT NOT NULL,
  action VARCHAR(64) NOT NULL,
  operator VARCHAR(64) NOT NULL,
  comment VARCHAR(256),
  operated_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  version INT DEFAULT 0
);

INSERT INTO sys_role (id, role_code, role_name) VALUES
  (1, 'ADMIN', CONVERT(0xE7AEA1E79086E59198 USING utf8mb4)),
  (2, 'REGISTRAR', CONVERT(0xE799BBE8AEB0E4BABAE59198 USING utf8mb4)),
  (3, 'TECHNICIAN', CONVERT(0xE68A80E5B888 USING utf8mb4)),
  (4, 'RADIOLOGIST', CONVERT(0xE8AF8AE696ADE58CBBE7949F USING utf8mb4)),
  (5, 'AUDITOR', CONVERT(0xE5AEA1E6A0B8E58CBBE7949F USING utf8mb4)),
  (6, 'PATIENT', CONVERT(0xE682A3E88085 USING utf8mb4))
ON DUPLICATE KEY UPDATE role_name = VALUES(role_name);

INSERT INTO sys_user (id, username, password_hash, display_name, enabled) VALUES
  (1, 'admin', 'bXJpLWRlbW8tc2FsdC0wMQ==:RXNbRsnC6O0uocAF8JkAe7ozzmURjU7gnQYBDpcs640=', CONVERT(0xE7B3BBE7BB9FE7AEA1E79086E59198 USING utf8mb4), 'Y')
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), display_name = VALUES(display_name);

INSERT INTO sys_user_role (id, user_id, role_code) VALUES
  (1, 1, 'ADMIN'),
  (2, 1, 'RADIOLOGIST'),
  (3, 1, 'AUDITOR')
ON DUPLICATE KEY UPDATE role_code = VALUES(role_code);

-- 业务样例数据已移除：系统启动后业务表为空，登录后由用户自行登记患者、检查、影像与报告。
-- 如需清空已有库中的历史样例数据，执行 scripts/db/clear-business-data.sql（保留登录账号）。
